enableTransparentWorkspaces: false

nodeLinker: node-modules

npmScopes:
  dhruv-m-patel:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${NPM_TOKEN-}"
    npmAlwaysAuth: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
