swagger: '2.0'
info:
  version: 1.0.0
  title: 'node-service'
  description: 'A simple backend service built with node.js and express'
basePath: '/api'
paths:
  /message:
    get:
      tags:
        - 'test-calls'
      description: 'A test api call that will get a message from node service'
      operationId: 'getMessage'
      responses:
        200:
          description: 'Service responded with a message'
          schema:
            $ref: '#/definitions/MessageResponse'
        default:
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/Error'
  /health:
    get:
      tags:
        - 'test-calls'
      description: 'A test api call for health checking the node service'
      operationId: 'checkHealth'
      responses:
        200:
          description: 'Service is healthy'
          schema:
            $ref: '#/definitions/MessageResponse'
        default:
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    required:
      - 'code'
      - 'message'
    properties:
      code:
        type: 'integer'
        format: 'int32'
      message:
        type: 'string'
  MessageResponse:
    required:
      - 'message'
    properties:
      message:
        type: 'string'
