openapi: '3.0.3'
info:
  version: 1.0.0
  title: starter-service
  description: Service contract for starter-service with OpenApi 3.0 specifications
servers:
  - url: 'http://localhost:8999/api'
tags:
  - name: Health
    description: Call to monitor the health of the service

security:
  - bearerAuth: []

paths:
  /health:
    $ref: health.yaml

components:
  schemas:
    $ref: schemas.yaml
