name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Ensure access
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{secrets.npm_token}}

      - name: Install packages
        run: |
          yarn config set npmScopes.dhruv-m-patel.npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmScopes.dhruv-m-patel.npmAlwaysAuth true
          yarn config set npmScopes.dhruv-m-patel.npmAuthToken $NPM_TOKEN
          yarn install --immutable
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true

      - name: Verify Code formatting and standards
        run: yarn ci:lint

      - name: Build app
        run: yarn ci:build

      - name: Run tests
        run: yarn ci:test
