name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install packages
        run: |
          yarn install
          yarn run bootstrap
      - name: Verify code formatting
        run: yarn run prettier:verify
      - name: Lint Code
        run: yarn run lint
      - name: Build app
        run: yarn run build
      - name: Run tests
        run: yarn run test:ci
