name: publish
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Grant access to package registry
        run: |
          yarn config set npmScopes.dhruv-m-patel.npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmScopes.dhruv-m-patel.npmAlwaysAuth true
          yarn config set npmScopes.dhruv-m-patel.npmAuthToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true

      - name: Install packages
        run: yarn install --immutable

      - name: Build app
        run: yarn ci:build

      - name: Publish Packages
        uses: changesets/action@v1
        with:
          publish: |
            yarn workspaces foreach --from '@dhruv-m-patel/*' npm publish --access public
            yarn changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
