name: build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install packages
        run: |
          yarn install
          yarn run bootstrap
      - name: Build app
        run: yarn run build
      - name: Publish
        run: yarn run publish
